spring:


  thymeleaf:
    mode: HTML5
logging:
  level:
    org:
      springframework: error
    com:
      codedrinker:
        dao: debug
server:
  port: ${port:8888}
  tomcat:
    max-http-header-size: 9999999

# 记得替换成你的id和secret
wechat:
  appid: wx4e03af15e71b5103
  secret: 92db4d63cba43124d0a2a5499c445679
## h2
#db:
#  url: jdbc:h2:~/jiuask
#  username: sa0
#  password: sa
#  driver: org.h2.Driver

# mysql
db:
  url: jdbc:mysql://localhost:3306/newhoteldb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
  username: root
  password: 123456
  driver: com.mysql.cj.jdbc.Driver